import Head from "next/head";

import { useDispatch, useSelector } from "react-redux";
import dynamic from "next/dynamic";
const Puzzle = dynamic(() => import("./../components/Puzzle"), { ssr: false });

import Timer from "../components/Timer";

export default function Home() {
  const gameInfo = useSelector((state) => state.gameInfo);
  const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Game | Puzzle Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="puzzle__container">
        {gameInfo?.loading ? (
          <p>Loading...</p>
        ) : (
          <>
            <Timer />
            <Puzzle />
          </>
        )}
      </section>
    </>
  );
}
