import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getRanking } from "../store/actions/gameActions";
import Link from "next/link";
import LeaderBoardRow from "../components/LeaderBoardRow";

export default function Home() {
  const dispatch = useDispatch();
  const gameInfo = useSelector((state) => state.gameInfo);

  useEffect(() => {
    dispatch(getRanking());
  }, []);

  return (
    <>
      <Head>
        <title>LeaderBoard | Puzzle Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="leaderBoard">
        {gameInfo?.loading ? (
          <p>Loading ....</p>
        ) : (
          <>
            <h1 className="leaderBoard__heading">Leader Board</h1>

            {gameInfo?.ranking?.map((rank, i) => (
              <LeaderBoardRow
                ranking={i + 1}
                level={rank.level}
                image={rank.image}
                key={i}
                name={rank.firstName}
              />
            ))}
          </>
        )}
      </section>
    </>
  );
}
